### ISSUE TITLE
Reorganize distro data

### ISSUE THREAD

**Issue by razzeee** [flatpak/flatpak.github.io#651]
While looking into supporting https://schema.org/HowTo on the flathub side of things it became apparent, that the data structure has some problems.

It would be nice to change the yaml a bit, currently we have:

```yml
- name: "Ubuntu"
  logo: "ubuntu.svg"
  info: <some html>
```

My current idea would be:

```yml
- name: "Ubuntu"
  logo: "ubuntu.svg"
  introduction: <some html>
  steps: 
	- <html>
	- <html>
```

Steps would need to be optional and they don't have the <li> tag.

What do you think?
